Vijaykv5/SnapGrid

index.html, src/MainSection.js
#11 Added the icon with  basic styling and link to the repo. linked to font awesome in index.html
=> added github icon and link to font awesome

package-lock.json, package.json, src/MainSection.js, src/components/menu/SelectionMenu.js, src/index.js, src/utils/links.js
=> format code with prettier

src/MainSection.js, src/components/menu/SelectionMenu.js
Use array index instead of the link.title so no need to traverse just to find the link item.
Closes #23
=> handleselection use index to avoid traversing to find the item.

src/MainSection.js
- Added a "Download" button to the user interface.
- Implemented functionality to allow users to download the displayed image.
- Enhanced the UI to provide a seamless download experience.
=> download button added for image

src/MainSection.js
=> fix initial scrolling effect

src/MainSection.js
Please refer to this 
https://github.com/Vijaykv5/Image-Searcher/issues/16
=> Banner Image Fix

src/MainSection.js, src/components/ImageCard/ImageCard.js
Fixed the issue of low quality images getting download. Downloads high quality image
**Changes**
- Changed the small quality download link to full
- Added icon for download instead of text
- Made separated component for the images card
- Added downloaded image link so that downlaoded image name will look like this: Image-searcher-(random8digitNumber)
=> Added Download Image Component

src/MainSection.js, src/components/menu/BackToTopButton.js, src/components/menu/ImageCard/ImageCard.js
Fixed the issue of low quality images getting download. Downloads high quality image
**Changes**
- Changed the small quality download link to full
- Added icon for download instead of text
- Made separated component for the images card
- Added downloaded image link so that downlaoded image name will look like this: Image-searcher-(random8digitNumber)
- Added Violet download button 
- Prettified Code
https://github.com/Vijaykv5/Image-Searcher/pull/40
=> Added Voilet Download button to download high quality images

README.md
In this pull request, I have introduced a new "Contributors" section within the README documentation. This addition aims to enhance the clarity and accessibility of the project's contribution for potential contributors and collaborators.
If you don't mind, put the hacktoberfest-accepted label if you accept.
=> [DOCS] Add Contributors section on README

src/MainSection.js, src/components/menu/SelectionMenu.js
Removed the horizontal scrollbar of topics from the UI for medium to large devices.
Closes #52 
**Changes**
Updated the ```overflow-x``` property of selectionMenu to hidden for large devices and makes it scroll for small devices for better UI. Also centers the selectionMenu topics.
**Checklist**
Add any additional comments, context, or information about this PR.
=> Removed horizontal scrollbar from UI

src/utils/links.js
The changes which are part of this PR target to enhance User Experience. Herein, spelling errors have been fixed along with minor grammatical enhancements. 
Grammatical enhancements
Fixes: https://github.com/Vijaykv5/Image-Searcher/issues/46
**Changes**
- Fixed spelling errors
**Before:**
**After:**
**Checklist**
None
=> fix(content): Fixed spelling errors

src/MainSection.js, src/components/menu/ImageCard/ImageCard.js
The changes which are part of this PR target to enhance User Experience. Herein, as soon as the user clicks on Prev/Next button, the new results appear but also the viewport aligns to make the new results on top, rightly bringing the focus of the users to recently fetched results.
Improvement for Next functionality
Fixes: https://github.com/Vijaykv5/Image-Searcher/issues/45
**Changes**
- Added scroll into view functionality for users on clicking prev/next nav buttons
(Screenshots cannot be added; Changes involve animated behavior)
**Checklist**
None
=> fix(nav): Enhanced prev/next button functionality

src/MainSection.js
This PR addresses the issue related to text placement when performing a manual image search using a word in our project. Currently, when users manually enter a search term, the text appears in an undesirable location, disrupting the user experience. This PR aims to enhance the user experience by ensuring that text placement is consistent and user-friendly, regardless of how the search term is entered.
This PR resolves the issue #67 related to text placement during manual image searches.
- Added logic to adjust the placement of text when users manually enter a search term for image search.
- Ensured that the text does not interfere with the images and is displayed in a user-friendly manner.
**Before**
**After**
This PR should significantly improve the user experience when manually …
=> Fixing Text Placement Issue in Manual Image Searches

src/MainSection.js, src/components/ShimmerLoading/ShimmerLoading.js
Added Shimmer UI for Banner and Images Card
Related Issue: https://github.com/Vijaykv5/Image-Searcher/issues/43
**Changes**
- Added Shimmer Loading Component for Image card and Banner
- Prettify Code
- Removed Extra Download function code
- Also changed the size of banner so that images card will appear perfectly
=> [Feature] Added Shimmer Loading to images card

src/MainSection.js, src/components/ShimmerLoading/ShimmerLoading.js
What does this PR do?
Added Shimmer UI for Banner and Images Card
Related Issue(s)
Related Issue: https://github.com/Vijaykv5/Image-Searcher/issues/43
Related PR: PR #82
Related PR: PR #55 
Changes
Added Shimmer Loading Component for Image card and Banner
Prettify Code
Removed Extra Download function code
=> [Feature] Added Shimmer Loading

src/MainSection.js
Provide a brief description of the purpose of this PR.
It changes the placeholder text from Try something search here to simply search herer
List any related issues or tasks that this PR addresses.
**Changes**
List the changes made in this PR. This could include new features, bug fixes, improvements, or any other modifications.
#91
If your PR includes visual changes, provide screenshots or GIFs to demonstrate the changes.
**Checklist**
Add any additional comments, context, or information about this PR.
=> [FEATURE] Changing the search box title #91

src/MainSection.tsx, src/components/menu/SelectionMenu.tsx
Updated the Dark Mode UI for the website and conflicts resolved.
Gave a Premium Outline Look for the Buttons
Added a glow effect on the search bar on being active
Special Styles for the selected Button in the dark mode.
Handled Issue #99
**Checklist**
=> Dark UI changes and Resolved Conflicts

src/MainSection.tsx, tailwind.config.ts
This PR fixes the image and description responsive issue in the mobile devices.
**Changes**
This PR improve the image and description responsiveness in the mobile devices.
Checklist
[*] I have read and followed the [contributing guidelines](https://github.com/Vijaykv5/SnapGrid/CONTRIBUTING.md).
[*] My code follows the project's coding style and conventions.
[*] I have added unit tests (if applicable) to ensure the code works as expected.
[*] I have updated the project documentation (if necessary).
Additional Comments
I had to hide the scroll bar using css because tailwind don't provide this feature yet.
By submitting this PR, I confirm that:
[*] I have reviewed my code and believe it is ready for merging.
[*] I understand …
=> fix: description and image responsive in mobile devices

src/MainSection.tsx
this PR fixes the overlapping issue when enabling the dark mode.
**Related Issue**
fixes #119 
**changes**
changes the screen width of **selection menu** from lg to xl 
**screenshots**
**Checklist**
✅I have read and followed the [contributing guidelines](https://github.com/Vijaykv5/SnapGrid/CONTRIBUTING.md).
✅ My code follows the project's coding style and conventions.
By submitting this PR, I confirm that:
✅ I have reviewed my code and believe it is ready for merging.
✅ I  understand that this PR may be subject to review and changes.
✅ I agree to abide by the code of conduct and contributing guidelines of this project.
=> fix the overlapping issue of dark mode

src/MainSection.tsx
In this pr, I have added the functionality of storing search query and page no in query params. If user searches something and reloads the page then his search result would not change as the search query and page no are fetched back from URL.
#132
**Changes**
Created a function to update the query params and it is called every time search input or page changes. Also added a useEffect hook with empty dependency so it is called only when page is loaded and never after that and inside it we fetch query params and make a call for images accordingly
<video src="https://github.com/Vijaykv5/SnapGrid/assets/84830429/95eac2f8-196e-4e72-ac4b-c435fbd649b3"/>
**Checklist**
NA
**By submitting …
=> Store search query and page no in query params

index.css, src/MainSection.tsx
Added Custom Purple Color Scrollbar and Custom Purple Selection Color.
**Changes**
I have also imported NoResults Component in MainSection.tsx which was missing.
**Checklist**
Add any additional comments, context, or information about this PR.
=> Added Custom Purple Color Scrollbar and Custom Selection Color

netlify.toml
Create redirect rule netlify for react-router
Fixes #144 
**Changes**
Add file netlify.toml for redirect rule router
Result:
https://github.com/Vijaykv5/SnapGrid/assets/51848196/1b0834e0-9a41-43d3-aa62-5b7d79e7864e
**Checklist**
Thank you for your response Sir @Vijaykv5 , and giving this task to me, I'm enjoyed to do it especially I can contribute to your project Sir @Vijaykv5 .
=> Fix redirect rule netlify

netlify.toml, src/Pages/Navbar.jsx, src/components/menu/Header.tsx
This PR resolves #147 
When you go to /search, you cannot go to Home Page until you edit the url
**Changes**
Added <Link to="/"> on Sendgrid Icon in navbar to redirect to home page and addef cursor pointer on hover
**Checklist**
=> [ADDED] Home page redirect

src/MainSection.tsx, src/components/menu/SelectionMenu.tsx
This PR resolves issue #153 
On searching a keyword that is in Selection Menu, Banner, description is not getting updated and button not getting activated
**Changes**
On searching a keyword that is in selection menu, Banner and description is changing and button is getting activated
Before Changes:
After changes:
Now, if the searched keyword is in the Selection Menu, that button gets highlighted and also the banner , description too changes accordingly.
**Checklist**
=> [UPDATED] Main Section to fix search bug

src/MainSection.tsx, src/components/menu/DarkModeButton.tsx
implemented the feature to remember the users preference of theme #172 and also solved the #115 issue where the image not found component was not loading when the user searched random  words
#115 solved the issue where the user was not able to see no images found when searching in non sensical words
#172  implemented the feature where the website remebers the theme preference of user using localstorage
**Changes**
implemented the feature where the website remembers the theme preferences of the user using localStorage also solved #115 where the error component was not showing when random words were searched
If your PR includes visual changes, provide screenshots or GIFs to demonstrate the changes. …
=> [feature] implemented functionality to remember users choice of theme #172 and solved issue #115

src/Pages/HomePage.jsx, src/utils/style.css
Adds Animation  on home page of the website
Resolves #171 
**Changes**
1.  Used 4 ref hooks to make the animation effect 
2. A single useEffect hook manages them so code is efficient
https://github.com/Vijaykv5/SnapGrid/assets/100792085/92d3a5a3-6fd6-40a0-9a63-da9a1957766d
**Checklist**
Add any additional comments, context, or information about this PR.
=> Animation on Home page 

src/Pages/HomePage.jsx
there is a default linear gradient for the background for the wholeviewport and in mobile devices or in desktop version when we resize the page the overflowed content was not getting this linear gradient instead its getting the default white background making the ui look non uniform #180 
#180 is the issue related to this task
**Changes**
just added a tailwind css class that gives the provided linear gradient background not only to viewport but to overflowed content too
before fixing the bug (mobile version)
before fixing the bug (desktop version)
after fixing the bug mobile version
after fixing the bug desktop version
**Checklist**
Add any additional comments, context, or …
=> fixed ui bg where overflowed contents background was white

src/Pages/DocsPage.jsx
the docs page of the snapgrid website was not responsive to smaller devices (mobile devices)
#181 is the related issue with this
**Changes**
made improvement in tailwind that makes the doc page responsive to mobile devices
before fixing the bug 
after fixing the bug 
**Checklist**
=> [bug]made docs page responsive to mobile devices

src/MainSection.tsx
This PR adds a feature to do instant search without using to press enter ley. But there is a catch it uses more api calls than usual.
Instead of searching as soon as the user start the search this pr uses other approach it gives result as soon as the user stop writing ,it is a better approach as it uses less api calls.
The search should happen as soon as I start typing #155
**Checklist**
- [✅] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [✅] My code follows the project's coding style and conventions.
- [✅] I have added unit tests (if applicable) to ensure the code works as expected.
- [✅] I have updated the project documentation (if necessary).
- [✅] I have reviewed …
=> Added instant search result without hitting the enter key
